.travis.yml, iatirulesets/text.py
This is shown on pages such as http://iatistandard.org/201/rulesets/standard-ruleset/
Note: This has not been tested. It is assumed to work first time.
=> [2.01] Create a human-readable output for sum rules

.travis.yml, iatirulesets/text.py
This is shown on pages such as http://iatistandard.org/201/rulesets/standard-ruleset/
Note: This has not been tested. It is assumed to work first time.
=> [2.02] Create a human-readable output for sum rules

rulesets/standard.json
=> Check that there is a non-empty narrative when there is no ref

meta_tests.sh, meta_tests/results_references.json, meta_tests/results_refs_bad.xml, meta_tests/results_refs_good.xml, rulesets/standard.json
Makes a fix to allow the tests added in #62 to pass.
=> Fix tests for results references rule

iatirulesets/__init__.py, iatirulesets/text.py, meta_tests.sh, meta_tests/result_indicator_baseline_selector_with_conditions.json, meta_tests/result_indicator_period_actual_selector_with_conditions.json, meta_tests/result_indicator_period_target_selector_with_conditions.json, meta_tests/results_indicator_baseline_value_bad.xml, meta_tests/results_indicator_baseline_value_good.xml, meta_tests/results_indicator_baseline_value_not_relevant.xml, meta_tests/results_indicator_period_actual_value_bad.xml, meta_tests/results_indicator_period_actual_value_good.xml, meta_tests/results_indicator_period_actual_value_not_relevant.xml, meta_tests/results_indicator_period_target_value_bad.xml, meta_tests/results_indicator_period_target_value_good.xml, meta_tests/results_indicator_period_target_value_not_relevant.xml, meta_tests/results_references.json, meta_tests/results_refs_bad.xml, meta_tests/results_refs_good.xml, rulesets/standard.json
Implements version 2.03 ruleset changes based on the [final technical proposal](https://discuss.iatistandard.org/t/final-technical-proposal-for-the-2-03-upgrade/1097).
=> Merge 2.03 development to 2.03 live branch

iatirulesets/__init__.py, meta_tests/forloop.json, meta_tests/forloop_bad.xml, meta_tests/forloop_good.xml, meta_tests/sector_percentage_sum.json, meta_tests/sector_percentage_sum_bad.xml, meta_tests/sector_percentage_sum_good.xml, rulesets/standard.json, testrules.php
Taken from @andylolz's #81 for version 2.03.
=> Sector percentage sum (version 2.01)

iatirulesets/__init__.py, iatirulesets/text.py, meta_tests.sh, meta_tests/period_time.json, meta_tests/period_time_bad.xml, meta_tests/period_time_good.xml, rulesets/standard.json, rulestable.py, testrules.php
=> [201] Add time limit rule for budget periods

SPEC.rst, iatirulesets/__init__.py, iatirulesets/text.py, meta_tests.sh, meta_tests/positive_decimal.json, meta_tests/positive_decimal_bad.xml, meta_tests/positive_decimal_good.xml, rulesets/standard.json, rulestable.py, testrules.php
=> Add new positive_decimal rule

SPEC.rst, iatirulesets/__init__.py, meta_tests.sh, meta_tests/between_dates.json, meta_tests/between_dates_bad.xml, meta_tests/between_dates_good.xml, rulestable.py
=> [2.01] Add rule: between_dates

iatirulesets/__init__.py, meta_tests.sh, meta_tests/time_limit.json, meta_tests/time_limit_bad.xml, meta_tests/time_limit_good.xml, rulesets/standard.json
=> [2.01] Adding time limit for org-files

.travis.yml, rulesets/standard.json
=> Run jsonlint on standard.json

README.rst, SPEC.rst, rulesets/standard.json, rulestable.py, schema.json
Addressing #97 and adding `between_dates` to `standard.json`
=> [2.01] Updating descriptive files to include new rules.

.travis.yml, iatirulesets/__init__.py, meta_tests/time_limit_bad.xml, meta_tests/time_limit_good.xml, requirements.txt, rulesets/standard.json
Addressing #126 and #127, adds dateutils to requirements.
=> [2.01] Fix time_limit rule, adding dateutils

iatirulesets/text.py
Fixing `text.py` before attempting deployment.
=> [2.01] Updating text.py to include all the new rules

.travis.yml, rulesets/standard.json
=> Fixed indentation in travis.yml

iatirulesets/text.py
Refs IATI/IATI-Standard-SSOT#288.
=> Fix indentation so ruleset renders better (v2.01)

iatirulesets/text.py
Refs IATI/IATI-Standard-SSOT#288.
=> Fix indentation so ruleset renders better (v2.02)

iatirulesets/text.py
Addresses https://github.com/IATI/IATI-Standard-SSOT/issues/288
=> [2.01] Fix ruleset rendering after adding new rules

iatirulesets/text.py
Addresses https://github.com/IATI/IATI-Standard-SSOT/issues/288
=> [2.02] Fix ruleset rendering after adding new ones

rulesets/standard.json
References https://github.com/IATI/IATI-Rulesets/issues/126#issuecomment-469240758
=>  Ensure rule is applied for _all_ activity budgets (v2.03)

meta_tests.sh, meta_tests/status_date.json, meta_tests/status_date_bad.xml, meta_tests/status_date_good.xml, rulesets/standard.json, schema.json
=> Checks to ensure status and dates correspond (v2.03)

rulesets/standard.json
=> (2.01) provider-org and receiver-org checked under atleast_one 

rulesets/standard.json
=> (2.02) provider_org and receiver_org checked under atleast_one

rulesets/standard.json
=> (2.03) provider_org and receiver_org checked under atleast_one #162

iatirulesets/text.py
=> (2.03) Render 'condition' when present in atleast_one rule

iatirulesets/text.py
=> (2.02) Render 'condition' when present in atleast_one rule

iatirulesets/text.py
=> (2.01) Render 'condition' when present in atleast_one rule

iatirulesets/__init__.py, iatirulesets/text.py, meta_tests.sh, meta_tests/range.json, meta_tests/range_bad.xml, meta_tests/range_good.xml, rulesets/standard.json, rulestable.py, schema.json
Min/max are optional so we can check if the value is at least/no more as well.
=> (2.01) Added range rule

iatirulesets/__init__.py, iatirulesets/text.py, meta_tests.sh, meta_tests/range.json, meta_tests/range_bad.xml, meta_tests/range_good.xml, rulesets/standard.json, rulestable.py, schema.json
Min/max are optional so we can check if the value is at least/no more as well
=> (2.02) Added range rule 

iatirulesets/__init__.py, iatirulesets/text.py, meta_tests.sh, meta_tests/range.json, meta_tests/range_bad.xml, meta_tests/range_good.xml, rulesets/standard.json, rulestable.py, schema.json
@Ocre42 we should talk about this before it goes into review! Also I need to do it for 2.01 and 2.02 as well
=> (2.03) Adding new range rule

iatirulesets/__init__.py, meta_tests/one_or_all.json, meta_tests/one_or_all_lang_good.xml, meta_tests/one_or_all_org.json, rulesets/standard.json
`@xml-lang` is the wrong attribute name. It should be `@xml:lang`.
=> Fix `@xml:lang` bug (version 2.03)

lib/schemata/non-embedded-codelist/Sector.xml
https://github.com/data4development/IATI-data-validator/issues/83
=> add missing sector code 12196

iatirulesets/text.py, requirements.txt
This PR implements https://github.com/IATI/IATI-Rulesets/pull/236 in v2.02
=> simplify xpath when comparing reduced_path for non paths cases
