SPEC.rst

Added missing formatting to rule headers. Fixed typos and grammatical errors. Changed a few things to make the content clearer to understand.

Fix typos and general content

---

rulesets/standard.json

The XPaths used in date_order `less` and `more` were previously incorrect
as they did not refer to valid XPaths containing dates at v2.02.

[#31] Fix XPaths used in date_order rules at 2.02

---

rulesets/standard.json

The XPaths used in date_order `less` and `more` were previously incorrect
as they did not refer to valid XPaths containing dates at v2.01.

[#31] Fix XPaths used in date_order rules at 2.01

---

rulesets/standard.json

The XPaths used in date_order `less` and `more` were previously incorrect
as they did not refer to valid XPaths containing dates at v1.04.

[#31] Fix XPaths used in date_order rules at 1.04

---

rulesets/standard.json

The XPaths used in date_order `less` and `more` were previously incorrect
as they did not refer to valid XPaths containing dates at v1.05.

[#31] Fix XPaths used in date_order rules at 1.05

---

iatirulesets/text.py

Fixes #30
The definition of `date_order` at http://iatistandard.org/202/rulesets/ruleset-spec/#rule-names states that `The date matched by less must be less than the date matched by more.`.
This means that today is not a valid value for `less` in this situation since today *is* today, rather than being before (well, `less than`) it.

[2.02] Fix dateorder text

---

iatirulesets/text.py

Fixes #30
The definition of `date_order` at http://iatistandard.org/202/rulesets/ruleset-spec/#rule-names states that `The date matched by less must be less than the date matched by more.`.
This means that today is not a valid value for `less` in this situation since today *is* today, rather than being before (well, `less than`) it.

[2.01] Fix dateorder text

---

iatirulesets/text.py

Fixes #30
The definition of `date_order` at http://iatistandard.org/202/rulesets/ruleset-spec/#rule-names states that `The date matched by less must be less than the date matched by more.`.
This means that today is not a valid value for `less` in this situation since today *is* today, rather than being before (well, `less than`) it.

[1.05] Fix dateorder text

---

iatirulesets/text.py

Fixes #30
The definition of `date_order` at http://iatistandard.org/202/rulesets/ruleset-spec/#rule-names states that `The date matched by less must be less than the date matched by more.`.
This means that today is not a valid value for `less` in this situation since today *is* today, rather than being before (well, `less than`) it.

[1.04] Fix dateorder text

---

rulesets/standard.json

When indicators are quantitative, a value must be specified.
Several separate Rules are added due to 1:many relationships.
Fixes #51

Make an attribute mandatory when particular codelist values are used

---

rulesets/standard.json

The result reference may be either at the result or indicator level, but not both.
This change is to be introduced with 2.03
Fixes #48

Add Rule to ensure result reference only at one level

---

rulesets/standard.json

Reverts IATI/IATI-Rulesets#56
A regex to represent a string containing some non-whitespace character cannot be represented in JSON due to the way backslashes are handled across each regex and JSON.
As such, this Rule is being removed from the set of Machine Actionable Rules since, well, it's not Machine Actionable within the current format!

Revert "Check that there is a non-empty narrative when there is no ref"

---

meta_tests.sh
meta_tests/results_references.json
meta_tests/results_refs_bad.xml
meta_tests/results_refs_good.xml

#54 adds untested rules to `version-2.03dev`. This PR adds tests for these new rules, which fail. This should be addressed before merging `version-2.03dev` to `version2.03`.
---
The 2.03 Schema suggests the [`result/reference`](https://github.com/IATI/IATI-Schemas/blob/fa0d7ba693d1a86eef5a8172cecd3f655067c3ea/iati-activities-schema.xsd#L1480) and [`result/indicator/reference`](https://github.com/IATI/IATI-Schemas/blob/fa0d7ba693d1a86eef5a8172cecd3f655067c3ea/iati-activities-schema.xsd#L1525) elements are 0..*. But using multiple `reference`s at either level causes the `no_more_than_one` rule to fail.
Refs #61.

Add a test for the results references rule

---

iatirulesets/text.py

Instead of e.g. “x and y and z”, human_list should now output “x, y and z”.

Tidy up human_list (v2.03)

---

iatirulesets/__init__.py
meta_tests/date_order.json
testrules.php

Addresses https://github.com/IATI/IATI-Rulesets/issues/31#issuecomment-395060938:
> While standard.json was updated for all versions to match [the signature pyIATI expects](https://github.com/IATI/pyIATI/blob/59588100911f4fd17a4012c0c2bc9632cc20efbd/iati/rulesets.py#L573) (i.e. a path to a date _*string*_), the relevant code that actually runs the ruleset tests in this repo (that [expects a path to a date _*element*_](https://github.com/IATI/IATI-Rulesets/blob/e77e6860ceba3be71d95c7ed95b9c78f3f29928e/iatirulesets/__init__.py#L40)) wasn’t updated. So this change breaks that.
> 
> The metatests on this repo weren’t updated either, so the green tick on these various PRs is misleading.
> 
> ~~This bug causes lots of errors for IATI-Stats, so it’s worth addressing.~~ UPDATE: Since …

Fix _parse_date code so that it expects a path to a date string, rather than to a date element (v2.03)

---

iatirulesets/__init__.py
meta_tests/date_order.json
testrules.php

Fix _parse_date code so that it expects a path to a date string, rather than to a date element (v2.02)

---

iatirulesets/__init__.py
meta_tests/date_order.json
testrules.php

Fix _parse_date code so that it expects a path to a date string, rather than to a date element (v2.01)

---

iatirulesets/__init__.py
meta_tests/date_order.json
testrules.php

Fix _parse_date code so that it expects a path to a date string, rather than to a date element (v1.05)

---

iatirulesets/__init__.py
meta_tests/date_order.json
testrules.php

Fix _parse_date code so that it expects a path to a date string, rather than to a date element (v1.04)

---

iatirulesets/__init__.py
meta_tests.sh
meta_tests/forloop.json
meta_tests/forloop_bad.xml
meta_tests/forloop_good.xml
meta_tests/sector_percentage_sum.json
meta_tests/sector_percentage_sum_bad.xml
meta_tests/sector_percentage_sum_good.xml
rulesets/standard.json
testrules.php

PR as per [this discuss thread](https://discuss.iatistandard.org/t/iati-rulesets-add-rules-for-sector-percentages-and-policy-marker-conditionals/1395). Sector percentages for a given vocabulary should add to 100%.
This adds that rule for DAC sector codes. It also adds the rule for other vocabularies, though the implementation (particularly in PHP) is perhaps a bit questionable.
---
Worth noting that for v1.0x, mentions of `@vocabulary = '1'` should be changed to `@vocabulary = 'DAC'`.

Add sector percentage rule (v2.03)

---

iatirulesets/text.py

Rules that involve `other_paths` are currently repeated in the
human-readable generated documentation. Jumping out of the loop fixes
this.
Refs #46.

Don’t repeat rules in the human-readable list (v2.02)

---

meta_tests/regex_bad.xml
meta_tests/regex_matches.json
meta_tests/regex_no_matches.json
rulesets/standard.json

See: http://discuss.iatistandard.org/t/iati-identifiers-should-not-be-allowed-to-contain-special-characters/649/8
Tests updated to use the actual regex rather than a toy example.

Regex should not match if a bad char is present (v2.02)

---

iatirulesets/__init__.py
iatirulesets/text.py
meta_tests.sh
meta_tests/date_now.json
meta_tests/date_now_bad.xml
meta_tests/date_now_good.xml
rulesets/standard.json
rulestable.py
testrules.php

Fixes #84, also defines `xsDateTimeRegex` to parse datetimes from the xml files.

[2.01] Add date_now rule for last-updated-datetime

---

.travis.yml
rulesets/standard.json
schema.json

#124 does a great job of (amongst other things) bringing schema.json up-to-date. This PR:
* fixes some small issues to make schema.json valid (f8511e1f; 2c632ae)
* fixes some small issues (including #128) to make standard.json validate against schema.json (709b1b4)
* stops running jsonlint on rulesets/standard.json on travis (49545a4), and instead…
* …makes travis perform schema validation on rulesets/standard.json, using schema.json (3146885)
You might not want to do the last two bits of this, because it could become a bit tiresome being forced to keep schema.json up-to-date (because travis builds will fail otherwise).

[2.01] Schema fixes

---

iatirulesets/text.py

- `This value must not contain a % sign` is rendered twice, without mention of the actual element that needs that rule applied
- `These values must not exist alongside...` was rendering lists, so added `human_list()` around them

Fix 2 descriptions that were not rendering correctly

---

iatirulesets/__init__.py
meta_tests/between_dates.json
meta_tests/between_dates_bad.xml
meta_tests/period_time_bad.xml
meta_tests/time_limit.json
rulesets/standard.json

Should address the remaining points on #126, also allows budgets to be EXACTLY one year. @andylolz you are welcome to test against this, just in case I may have missed something else!

[2.01] Rearrange standard.json and fine-tune time_limit

---

iatirulesets/__init__.py
rulesets/standard.json

Addressing #114, also changes `tree.findall` to `tree.xpath` to solve multiple element issues as per [this comment](https://github.com/IATI/IATI-Rulesets/issues/126#issuecomment-463603508)

[2.02] Policy-marker rules

---

iatirulesets/__init__.py
rulesets/standard.json

- `policy-marker/@significance` is a back port from `2.02` (and hasn't been assessed for `2.03` yet as the team has been out ill most days)
- `tree.findall` -> `tree.xpath` is a back port of a fix that already exists in `2.03` and `2.02` (as of today)

Add policy-marker/@significance rule and fix tree.findall()

---

meta_tests/evaluates_to_true.json
meta_tests/evaluates_to_true_bad.xml
rulesets/standard.json

Added more elements to check for no percent sign.
Updated the positive_decimal check to now check the inclusive range between 0.0 and 100.0
Fixes #147

Ensure percentages are a number between 0 and 100

---

meta_tests/if_then.json
meta_tests/if_then_bad.xml
rulesets/standard.json

Adds a new set of cases under the `if then` conditions.
Explanation why we check `number() = number()`:
`number(value) = number(value)` is true if `value` is a number, or a string that represents a number.
Whenever `value` cannot be used as a number, then `number(value)` is NaN and NaN is not equal to any other value, even to itself.
The above expression is true only for `value` whose value can be used as a number, and false otherwise.
Simply checking (like I originally did) for `number(value) = value` throws an operator error in XPath2.0, while `number(value)` isn't enough of a test because it checks that `value` is a non-zero numeric item, but we want 0 to be included as well.

Added new quantitative @value rule check

---

iatirulesets/__init__.py
meta_tests/one_or_all.json
meta_tests/one_or_all_lang_good.xml
meta_tests/one_or_all_org.json
rulesets/standard.json

`@xml-lang` is the wrong attribute name. It should be `@xml:lang`.
This is the same as #179, but for v2.02.

Fix `@xml:lang` bug (version 2.02)

---

iatirulesets/__init__.py
meta_tests/one_or_all.json
meta_tests/one_or_all_lang_good.xml
meta_tests/one_or_all_org.json
rulesets/standard.json

`@xml-lang` is the wrong attribute name. It should be `@xml:lang`.
This is the same as #179, but for v2.01.

Fix `@xml:lang` bug (version 2.01)

---

.travis.yml

As part of the process of moving from python 2.x -> python 3.x

Removing python 2.7 from travis tests

---

.travis.yml

As part of the process of moving from python 2.x to python 3.x

Remove python 2.7 from Travis tests (v2.02)

---

rulesets/standard.json

These rules:
https://github.com/IATI/IATI-Rulesets/blob/d49b82b821e7ed23d62da1a6767d9dd7cdd310b6/rulesets/standard.json#L7-L9
…have all been replaced by correct versions here:
https://github.com/IATI/IATI-Rulesets/blob/d49b82b821e7ed23d62da1a6767d9dd7cdd310b6/rulesets/standard.json#L127-L147
The original versions haven’t been removed from the v2.03 branch, though. This PR does that.
There’s no need to duplicate this PR for v2.01 or v2.02, since the problem doesn’t exist on those branches.

Remove duplicate rules (v2.03)

---

lib/schemata/1.01/iati-activities-schema.xsd
lib/schemata/1.02/iati-activities-schema.xsd
lib/schemata/1.03/iati-activities-schema.xsd
lib/schemata/1.04/iati-activities-schema.xsd
lib/schemata/1.05/iati-activities-schema.xsd
lib/schemata/2.01/iati-activities-schema.xsd
lib/schemata/2.02/iati-activities-schema.xsd

An issue in the script I used to copy the iati-activities-schema.xsd files for v2.02 and previous meant that these were not updated in the IATI-Rulesets master branch of the .xslt style rules and therefore not included in the latest Validator version.
Previous PR:
https://github.com/IATI/IATI-Rulesets/pull/235/

update activities schemas for previous versions

---

rules/iati.xslt

When trying to apply iati.xslt transform on an IATI xml file with Saxon-JS the codelists rules were not being applied. I traced this back to the following error:
`xsl:message evaluation at iati.xslt#-1 failed: XError:Circularity in global variable Q{}iati-codelists; code:XTDE0640`
This seems to have occurred because the following templates were declared before the "iati-codelists" variable was defined.
```
<xsl:template match="codelist" mode="get-codelists">
<xsl:copy>
<xsl:copy select="@name"/>
<xsl:apply-templates select="//code" mode="get-codelists"/>
</xsl:copy>
</xsl:template>
<xsl:template match="code" mode="get-codelists">
<xsl:copy>{.}</xsl:copy>
</xsl:template>  
<xsl:variable name="iati-codelists">
<codes version="2.03">
<xsl:apply-templates …
```

re-order codelist apply-template to fix circularity error in saxonjs
